name: vaishnav_new

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a simple command
        run: echo "Code is now checked out"
    
