name: Node.js Package
on:
  workflow_dispatch:   # 👈 enables manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: |
          echo "Starting script one"
          ls -la
          pwd

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: second job
        run: |
          echo "Starting script two"
          ls -la
          pwd
